### ISSUE TITLE
0-60 - Ingress Gateway Error doesn't match text

### ISSUE THREAD

**Issue by shamusx** [eitansuez/killercoda-scenarios#1]
Page: Ingress
Task: Ingress Gateway
Feedback:
- Access gateway via port 1234 - returns bad gateway: HTTP/1.1 502 Bad Gateway (instead of connection refused)
- Also port forward loses connection to pod after 503 response

https://github.com/eitansuez/killercoda-scenarios/blob/master/istio-0to60/ingress.md

**Comment by eitansuez** [comment]
yes, i noticed this. basically when the gateway is not configured you want it to refuse the connection. i suppose a 502 bad gateway is an indication that you can't get in unless someone explicitly configures the Gateway resource. and that's a good learning experience. but the unfortunate thing is that it trips the port-forward command. i will sidestep the issue by simply waiting until Gateway is configured to start playing with probing the ingress.
