### ISSUE TITLE
0-60 - Port-Forward need to be setup again

### ISSUE THREAD

**Issue by shamusx** [eitansuez/killercoda-scenarios#2]
Page: Ingress
Task: Create a Gateway Resource
Feedback:
Need to run the port forward again before step 3 (lost connection to pod in previous step)

Notes:
- Should this be run in different tab? Or Background (&) to avoid scrolling away from place (since port forward looks to close in Ingress Gateway step)
- There is a note in Observability section for port-forward that could maybe be reused

https://github.com/eitansuez/killercoda-scenarios/blob/master/istio-0to60/ingress.md

**Comment by eitansuez** [comment]
yes, i noticed this.  basically when the gateway is not configured you want it to refuse the connection.  i suppose a 502 bad gateway is an indication that you can't get in unless someone explicitly configures the Gateway resource.  and that's a good learning experience.  but the unfortunate thing is that it trips the port-forward command.  i will sidestep the issue by simply waiting until Gateway is configured to start playing with probing the ingress.
